### ISSUE TITLE
Implement application to run the HTML web server

### ISSUE THREAD

**Issue by mamo6538** [kbiggs/final-project-assignment-kbiggs#11]
Add the tornado web server capabilities to the main python master code to handle sending data to the HTML web server.

DoD: The full program works as expected on both Rpi3 and Rpi4

Blockers: #12 #5  

Completed: [repo](https://github.com/cu-ecen-aeld/final-project-mamo6538) for code of server and html and the final [commit](https://github.com/cu-ecen-aeld/final-project-mamo6538/commit/d1129c1bf855f7749fb24450704debdace5187da)

**Comment by kbiggs** [comment]
Application running on RPi 3:
- Command line output showing connection to Tornado server and interactions for getting real-time data and updating settings

![Image](https://github.com/kbiggs/final-project-assignment-kbiggs/assets/26662948/c27f5c9f-6945-4242-8c72-8246a9bb91b5)

- Screenshot showing HTML page with real-time data for pressure sensors 

![Image](https://github.com/kbiggs/final-project-assignment-kbiggs/assets/26662948/0c3c71d0-c461-43f8-beef-4b81c2b26b99)

**Comment by mamo6538** [comment]
The startup page:

![Image](https://github.com/kbiggs/final-project-assignment-kbiggs/assets/98003612/3322256f-b190-40e3-ac2a-5fb66a236f61)

Testing every button and receiving data:

![Image](https://github.com/kbiggs/final-project-assignment-kbiggs/assets/98003612/c84469a6-ceea-405d-a67a-857cb2756ba6)

Testing Alarms and settings:


![Image](https://github.com/kbiggs/final-project-assignment-kbiggs/assets/98003612/9d4275ca-0740-426d-8234-3c5031ce67db)
