### ISSUE TITLE
Modify python application based upon which RPi is being used

### ISSUE THREAD

**Issue by kbiggs** [kbiggs/final-project-assignment-kbiggs#14]
Modify the overall python application to read expected sensors and simulate sensor readings based upon which RPi is being used

DoD: The same master program can run successfully on each RPi based upon which sensors are connected.

Blockers: #3 , #13 , #9 , #12 , and maddie needs to test on rpi4b

Completed: Python application gathers sensor data and performs basic automation actions for both RPis based off command line parameter. Following commits contain the majority of the work to split the application per Pi. [Commit](https://github.com/cu-ecen-aeld/final-project-mamo6538/commit/5af9ee8de08a6485f854f607b7a1abecb36e22b2), [Commit](https://github.com/cu-ecen-aeld/final-project-mamo6538/commit/98b0808dbc84907fd2350a7faaa215c83125806d), [Commit](https://github.com/cu-ecen-aeld/final-project-mamo6538/commit/5408863f155d860c0a8285c5b6cebd128f354c68)

**Comment by mamo6538** [comment]
Working on rpi4b:


![Image](https://github.com/kbiggs/final-project-assignment-kbiggs/assets/98003612/824536e1-f0bb-47e3-8ae9-dc49638f6ed3)

**Comment by kbiggs** [comment]
Program working on RPi 3:


![Image](https://github.com/kbiggs/final-project-assignment-kbiggs/assets/26662948/b48b5c72-7747-4de8-9c79-470027e7391e)
