### ISSUE TITLE
Consolidate repos

### ISSUE THREAD

**Issue by mamo6538** [kbiggs/final-project-assignment-kbiggs#18]
Implement defines to consolidate the buildroot implementation into 1 repo - [buildroot repo](https://github.com/cu-ecen-aeld/final-project-kbiggs).  Make sure to use a branch.

DoD: Can use buildroot repo to build an rpi4b image that loads onto rpi4b.  Also can use the kbiggs repo to build an rpi3b image that loads onto rpi3b board.

Blocker: Need Katie to test on rpi3b

Completed: Changes in [initial script commit](https://github.com/cu-ecen-aeld/final-project-kbiggs/commit/105815fbc67682fe457835ed78a23198ba8597d2) and [script updates commit](https://github.com/cu-ecen-aeld/final-project-kbiggs/commit/4a183dc71f890cb985fb6d76b90aa18eca5c4cd5) allowed us to generate the kernel image for either raspberry pi from the same buildroot repo.  These changes were merged into the [main branch](https://github.com/cu-ecen-aeld/final-project-kbiggs/commit/4f54aea81c6035549dd94024553bcf22ef72dbc1).  In addition, changes were made to clean up the [module repo](https://github.com/cu-ecen-aeld/final-project-mamo6538) to keep the repos organized and consolidated.

**Comment by kbiggs** [comment]
RPi 3B booting successfully from image generated with the 'consolidated_repos' branch of the buildroot repo.

**Comment by mamo6538** [comment]
I've tested and with a ./clean.sh and then ./build.sh 4 (x2), the RPi 4B also successfully booted.
