### ISSUE TITLE
Add NGINX to main buildroot repo

### ISSUE THREAD

**Issue by mamo6538** [kbiggs/final-project-assignment-kbiggs#19]
Add the nginx and html setup to the main buildroot repo

DoD: can get the rpi3b and rpi4b to each host an HTML webpage.

Blockers: Need #18 working before Maddie can test on rpi4b

Completed: nginx and html changes were implemented for RPi 3 with [commit](https://github.com/cu-ecen-aeld/final-project-kbiggs/commit/6dfe7464b9778c6ca737ff037e1b0f90603772ae)

**Comment by kbiggs** [comment]
Image of nginx hosted HTML page, hosted off of RPi3B. I could connect to the HTML page via my laptop


![Image](https://github.com/kbiggs/final-project-assignment-kbiggs/assets/26662948/2152fc16-77aa-4723-8746-ebab3a6c0f6d)
